name: Website

on:
  push:
    branches:
      - main

jobs:
  html:
    runs-on: ubuntu-latest
    steps:
    - uses: mattpolzin/idris-katla-action@0.1.0
      with:
        MARKDOWN_PATH: ./md
        HTML_PATH: ./html
    - name: Deploy HTML
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: gh-pages
        folder: html
        git-config-name: Github Actions

